"""
teste2
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    return

default_args={
    "owner": "João Moura Jr,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-12-20", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "João Moura Jr": "mailto:jvjmoura@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm4rg6wta179s01inri3fm15w/cloud-ide/cm4rgcmac17v201ljqbx8fzrx/cm4vzx1450lf101kt42rp7f8f",
    },
)
def teste2():
    python_1 = python_1_func()

dag_obj = teste2()
